# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Log-Log4perl-ConfigByInifile
version:      0.04
version_from: lib/Log/Log4perl/ConfigByInifile.pm
installdirs:  site
requires:
    Config::IniFiles:              
    FindBin:                       
    Log::Log4perl:                 
    Params::Validate:              
    Test::More:                    
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
